apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: frontend
    files:
      - html/index.html

generatorOptions:
  disableNameSuffixHash: true

